apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: djangoregistry01.azurecr.io/raaaaaaai/django-backend/1.0:latest
          ports:
            - containerPort: 8000


