apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: DjangoRegistry01.azurecr.io/raaaaaaai/django-backend/$(Build.BuildId)
          ports:
            - containerPort: 8000


